### ISSUE TITLE
你好,支持分页吗?文章多了,可以分页吗?

### ISSUE THREAD

**Issue by ricardo0624** [shenliyang/hexo-theme-snippet#1]
因为现在看到你的示例网站的文章比较少,看不出来,所以问一些?
如果支持分页了,是无限下拉(如果找特定的文章,刷新以后就没了),还是数字链接,如果就是想找第几页的文章的话,不用每次都下拉

**Comment by shenliyang** [comment]
你好，该主题支持前后页和点击数字翻页，不采用下拉刷新形式。对于分页设置可以在config.yml配置。感谢您的支持和反馈！

**Comment by Greefe** [comment]
你好，不支持categories和tags的显示么，我上一个主题是random支持显示，这个主题没有显示，按照文档上的配置都配置好了，就是没有显示。

**Comment by shenliyang** [comment]
#### 你好，主题支持categories和tags功能，请检查Hexo根目录下的 config.yml 配置情况：
``` yml
tag_dir: tags
category_dir: categories
```
#### 并与主题导航的链接配置一致。
请参考文档配置：[https://hexo.io/zh-cn/docs/configuration.html](https://hexo.io/zh-cn/docs/configuration.html)
