### ISSUE TITLE
能有时间完善搜索功能吗

### ISSUE THREAD

**Issue by shay-developer** [shenliyang/hexo-theme-snippet#10]
我觉得博客文章多的话 搜索功能还是需要的 麻烦有时间补充下呗  谢谢

**Comment by wiliam2015** [comment]
你可以看看我fork的，自己修改了增加了本地搜索功能等一些常用的功能：https://github.com/wiliam2015/hexo-theme-snippet

**Comment by eacdy** [comment]
可以看看我的<https://github.com/itmuch/hexo-theme-itmuch>
