### ISSUE TITLE
移动端赞赏功能

### ISSUE THREAD

**Issue by CatchaOG** [shenliyang/hexo-theme-snippet#107]
移动端赞赏功能，点击无效

**Comment by shenliyang** [comment]
是否可以提供下相关截图和手机型号等信息

**Comment by CatchaOG** [comment]
iphone7，如果我不配置LIVE2D挂件的话，点击赞赏按钮无效。我感觉可能是冒泡等原因
![img](https://user-images.githubusercontent.com/38447309/51425605-607bd880-1c19-11e9-882e-40eeadd7a8d2.jpg)
