### ISSUE TITLE
文章摘要md 文件无法编译

### ISSUE THREAD

**Issue by Lee981265** [shenliyang/hexo-theme-snippet#110]
![image](https://user-images.githubusercontent.com/29849554/51519361-b3dd6900-1e5b-11e9-8e29-6c56ac9d4a62.png)

正文是正常的
![image](https://user-images.githubusercontent.com/29849554/51519382-ca83c000-1e5b-11e9-8653-dbb8fcd38395.png)

**Comment by shenliyang** [comment]
因为摘要部分内容会对html原生标签进行过滤包括(<  > )，避免一些不要问题出现。
解决方案：修改源码archive.ejs文件，去掉标签过滤功能(非常不推荐, 可能会引发更多问题)
```
<%= truncate(strip_html(post.content), {length: theme.excerptLength || 120, separator: ''}) %>
改为：
<%= truncate(post.content, {length: theme.excerptLength || 120, separator: ''}) %>
```
