### ISSUE TITLE
图片不能正常显示及数学支持

### ISSUE THREAD

**Issue by yangql881012** [shenliyang/hexo-theme-snippet#111]
你好，请问一下，图片不能显示是什么问题。
如果要支持数学公式的话，需要做什么操作，谢谢

**Comment by EscapeLife** [comment]
The directory structure of the project should look like this, so the _post directory for blog posts and the images directory for images.
 
![image](https://user-images.githubusercontent.com/16237571/51610069-c38da800-1f56-11e9-9fce-ec7cef5fac2e.png)

Used in this article, it should look like this.

```bash
![images](/images/new-images.png)
```

**Comment by shenliyang** [comment]
@EscapeLife 👍

**Comment by shenliyang** [comment]
@yangql881012  如果需要数学公式，建议搜索Mathjax或者latex
