### ISSUE TITLE
关于TOC的一些小建议

### ISSUE THREAD

**Issue by eacdy** [shenliyang/hexo-theme-snippet#113]
目前开启TOC后，会强制关闭其他widget，这个感觉不太优雅，但是TOC又能显著提升阅读体验。
建议：
1. widget弄两个开关……首页一个开关，内页一个开关……这个感觉只要在`_partialtoc.ejs` 判断开关就可以了。
2. 建议将搜索按钮挪到导航栏上。否则，一旦开启TOC，读者要搜索文章必须得跳到首页去玩，感觉很变态啊……
3. 下下图的空白和首页不一致，希望能够修正一下。我布局非常慢，不然可以直接贴我的代码……
![image](https://user-images.githubusercontent.com/9031050/51662862-21220300-1ff0-11e9-9bf0-fa1663c560c7.png)

最后，我目前改成这样了：可以预览下： http://www.itmuch.com/spring-cloud/finchley-17/ 
感觉还可以，就是那个搜索不大满意……

===
个人感觉啊：
1. 将搜索放到导航栏，这样不影响widget
2. TOC不应该和其他widget有量子纠缠，我开我的，你开你的……互不影响。
3. wiget应该在内页、首页都有开关配置，这样就能非常灵活，能适应各种需求。

**Comment by shenliyang** [comment]
感谢您的反馈，这些问题确实还需要规划优化，为了主题简洁轻量，所以没有引入JQuery，一直比较限制发展。关于上面提到的问题回复如下:
1.也尝试过把搜索放到导航栏，也有网友改版过，但手机端效果还是不太满意。
2.关于布局右侧，文章详情页为TOC,其他部分为widget，当时想法是让用户进去文章后，关注点能停留在TOC，文章底部放些相关文章推荐能更好一些。
做一个主题或许不难，但是众口难调要是做到让每个人都满意，确实还需努力。如果每个布局分配每个终端的每次细节都能考虑到就更好了。再次感谢您的反馈。
