### ISSUE TITLE
搜索引擎收录问题

### ISSUE THREAD

**Issue by liaochenlanruo** [shenliyang/hexo-theme-snippet#116]
请问大神，我研究了好久，一直没有搞定百度收录问题 ，网上的教程都是针对next主题的，请大神指点，谢谢！祝新春快乐！

**Comment by ackurdeeve** [comment]
最简单的方式就是把生成的sitemap放在另外一个地方，然后修改dns页面规则，用301重定向到哪里去。

**Comment by shenliyang** [comment]
首页安装hexo-generator-sitemap插件，然后
在博客根目录下找到_config.yml文件，添加如下代码:
```
sitemap:
path: sitemap.xml
```
执行hexo g生成静态页面，再然后执行hexo s启动服务
打开 http://localhost:4000/sitemap.xml即可看到效果，弄好之后你就可以到各大搜索引擎提交sitemap站点地图了
