### ISSUE TITLE
Gitalk显示为未找到相关的 Issues 进行评论

### ISSUE THREAD

**Issue by ackurdeeve** [shenliyang/hexo-theme-snippet#117]
我的域名为自定义域名www.ackurdeeve.com；repo地址为ackurdeeve.github.io

Gitapp设置
Homepage URL： https://github.com/ackurdeeve/ackurdeeve.github.io
Authorization callback URL： https://www.ackurdeeve.com

clientID，clientSecret，repo设置打引号和没打引号都试过了，最后都显示未初始化。是否是因为自定义域名和repo地址不一致导致的？

**Comment by ackurdeeve** [comment]
尝试把Homepage URL： https://ackurdeeve.github.io  可以正常调用githubapp， 但问题没解决。
点击issues直接进入repo

**Comment by shenliyang** [comment]
首先需要根据自己网站情况配置回调地址，每个页评论需要有github对应的Issues,建议看下 :[gitalk](https://github.com/gitalk/gitalk/blob/master/readme-cn.md)
