### ISSUE TITLE
建议添加双语功能

### ISSUE THREAD

**Issue by ackurdeeve** [shenliyang/hexo-theme-snippet#118]
https://upwnothing.github.io/2018/09/13/Hexo-Bilingual-Blog/

**Comment by ackurdeeve** [comment]
<div id="google_translate_element"></div>
	<script>
		function googleTranslateElementInit() {
			new google.translate.TranslateElement({
				pageLanguage : 'en',
				autoDisplay : false,
				gaTrack : true,
				layout : google.translate.TranslateElement.InlineLayout.SIMPLE
			}, 'google_translate_element');
		}
	</script>
	<script
		src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
	Index
	<br>
--------------------- 
作者：iteye_16738 
来源：CSDN 
原文：https://blog.csdn.net/iteye_16738/article/details/82236885 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by EscapeLife** [comment]
Feeling unnecessary 😝

**Comment by ackurdeeve** [comment]
> Feeling unnecessary 😝

看了您的博客界面，很受启发。想问问您的留言功能是怎么处理的？我也很想有您的那个留言系统 谢谢

**Comment by EscapeLife** [comment]
@ackurdeeve Comes with the hexo-theme-snippet template. 

`https://github.com/shenliyang/hexo-theme-snippet#1-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE`

```bash
### 来必力(默认选项)
livere:
  enable: true
  livere_uid:
```
