### ISSUE TITLE
点击分类或者标签时,顶端的分类和标签的样式

### ISSUE THREAD

**Issue by nygula** [shenliyang/hexo-theme-snippet#120]
\themes\hexo-theme-snippet\source\css\less
增加如下样式
.main-content{
	
	.title {
        margin-top: 0;
        padding-bottom: 12px;
        margin-bottom: 1px;
        position: relative;
		background: white;
		padding-top: 10px;
		padding-left: 10px;
        &:after {
            content: "";
            width: 90px;
            height: 1px;
            background: @theme_color;
            position: absolute;
            left: 0;
            bottom: -1px;
        }
    }
}

\themes\hexo-theme-snippet\layout\_partial\archive.ejs
<% if(page.tag) { %>
   <h3 class="title"><%= page.tag %></h3> 
<% } if(page.category) { %>
   <h3 class="title"><%= page.category %></h3> 
<% } else { %>
<% } %>

**Comment by shenliyang** [comment]
谢谢，收到
