### ISSUE TITLE
希望添加留言板功能

### ISSUE THREAD

**Issue by longyating** [shenliyang/hexo-theme-snippet#123]
需求就是新建了guestbook后的index.md,无法拥有评论区。
感觉这个页面还是挺实用的。建议完善。

**Comment by EscapeLife** [comment]
@longyating Do you need to add new articles that visitors can comment on? like this?

![image](https://user-images.githubusercontent.com/16237571/53573784-379c1b00-3ba9-11e9-9b12-a6915b24618b.png)

Refer to this link: `https://github.com/shenliyang/hexo-theme-snippet#1-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE`

```bash
## 主题评论

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  labels:
  perPage:
  maxCommentHeight:

### 来必力(默认选项)
livere:
  enable: true
  livere_uid:

......
```

**Comment by longyating** [comment]
我研究出留言板功能啦！直接新建一个hexo new "留言板"。然后hexo d.提交后，复制该页面的网址。_config.yml menu中新增一个留言板选项卡，其url就用刚刚复制的连接。然后就真的成功啦！喜极而泣。附上自己的网址，以供学习交流。https://www.longyating.com

**Comment by EscapeLife** [comment]
一个有点文艺的工科女 😄

**Comment by wangyongjie2017** [comment]
我捣鼓了一个留言板的功能，需要的可以参考一下 [我的留言板](http://wangyongjie.top/message/) 哦，用的是`valine`留言插件，大概思路是把需要的`html`代码直接放到`md`文件中即可。另外还自定义了[404页面](http://wangyongjie.top/404/)，当访问不存在的页面时候，会跳转到自定义的404页面，主题作者大大可以更新主题的的时候考虑加入自定义404页面，谢谢大佬。
