### ISSUE TITLE
右侧的小标题栏还是英文的，已经设置过language为zh-CN了，但还是不行

### ISSUE THREAD

**Issue by wyd288** [shenliyang/hexo-theme-snippet#126]
这个语言是自己识别的吗?还需要增加什么文件吗？

**Comment by shenliyang** [comment]
需要在您的hexo配置文件_config.yml中修改
``` yml
language: zh-CN
```

**Comment by EscapeLife** [comment]
如果需要其他语音的支持，如日文/法语，可以通过自动配置文件。可以参考如下配置文件自行修改。`https://github.com/shenliyang/hexo-theme-snippet/blob/master/languages/zh-TW.yml`
