### ISSUE TITLE
站内搜索失效 如何配置？

### ISSUE THREAD

**Issue by wangsunwuji** [shenliyang/hexo-theme-snippet#129]
### 问题是这样的

**当我把站点配置在 yoursite.com/home 下的时候，站内搜索就没有作用了(配置在yoursite.com下有搜索结果)，请问需要怎么配置?**貌似是缺少一个content.json文件

![3](https://user-images.githubusercontent.com/44321189/56280187-41b7b000-613c-11e9-8a00-d43aa47b966e.png)

![1](https://user-images.githubusercontent.com/44321189/56272426-42951580-612d-11e9-9b1e-0d3de9db300e.png)

![4](https://user-images.githubusercontent.com/44321189/56280457-d8846c80-613c-11e9-8d4b-55ed70aee977.png)

**Comment by shenliyang** [comment]
这个问题已经解决了，请拉取下最新的代码。
