### ISSUE TITLE
建议增加图片点击放大浏览功能

### ISSUE THREAD

**Issue by spygg** [shenliyang/hexo-theme-snippet#130]
现在页面中图片有时候会看不清,建议增加图片点击放大浏览功能,或者在新页面中打开链接,谢谢了!

**Comment by spygg** [comment]
已添加,具体见我的博客[给所有的图片加上连接](https://spygg.github.io/

**Comment by shenliyang** [comment]
感谢 建议已收到。

**Comment by shenliyang** [comment]
效果非常棒 :thumbsup:
