### ISSUE TITLE
可以不使用Gulp构建吗

### ISSUE THREAD

**Issue by immno** [shenliyang/hexo-theme-snippet#131]
各人感觉 gulp 依赖包比较烦，解决一个又一个依赖
在部署部分 官方提供了`hexo d` 为什么还有再加一个`_travis.sh` 部署文件，适配官方的不更好吗？

**Comment by immno** [comment]
我在调试的时候直接使用`hexo clean && hexo g && hexo s -p 4000`没问题，使用`hexo clean && hexo g && hexo d`部署就有问题，文件内容都为空

**Comment by shenliyang** [comment]
你好，首先，您可以完全使用hexo d生成静态文件部署即可，不使用gulp 和travis 没有问题。

1. 为什么主题使用Gulp？

- 开发一个主题很难满足所有的要求和个性化部分，为了二次开发扩展和自己个性化定制更方便。
- 使用gulp是为更好的优化静态html css 和js部分，比如，hexo d 生成静态文件会有很多空格等其他情况

2. 为什么是用_travis.sh？

- Travis自动化持续集成工具，_travis.sh只是一个配置的linux sh脚本。具体功能可以对照Jenkins的功能，不使用不影响主题的正常使用。
