### ISSUE TITLE
站内搜索只能在首页正常使用，其它页面无法使用

### ISSUE THREAD

**Issue by steley** [shenliyang/hexo-theme-snippet#135]
你好，

本地站内搜索除在首页搜索正常外，在其它页面无法搜索。
***
更新于2019年5月16 18:46
- 首页搜索
[![Selection_021.png](https://i.loli.net/2019/05/16/5cdd3f3362f2897522.png)](https://i.loli.net/2019/05/16/5cdd3f3362f2897522.png)
- 归档页搜索
[![Selection_022.png](https://i.loli.net/2019/05/16/5cdd3f332fc5986263.png)](https://i.loli.net/2019/05/16/5cdd3f332fc5986263.png)

**Comment by shenliyang** [comment]
请提供更多信息

**Comment by steley** [comment]
> 请提供更多信息

已重新编辑，辛苦
