### ISSUE TITLE
gitalk配置出错

### ISSUE THREAD

**Issue by hanmingkang** [shenliyang/hexo-theme-snippet#137]
![1558348400(1)](https://user-images.githubusercontent.com/19572365/58320865-3cdad000-7e4f-11e9-8d23-7969efb19b9b.png)

应该是这样，而不是String

**Comment by Syngnath** [comment]
同志你的图炸了

**Comment by Syngnath** [comment]
> 应该是这样，而不是String

同志你的图炸了
