### ISSUE TITLE
请问如何增大一级标题前的空间？太挤了

### ISSUE THREAD

**Issue by Syngnath** [shenliyang/hexo-theme-snippet#138]
> 请先确认以下情况：
- [x] 拉取主题最新代码，问题依然存在。
- [x] 已经搜索Issues历史记录，并阅读过：[主题常见问题](https://github.com/shenliyang/hexo-theme-snippet#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] 提Issues前建议先阅读：[《你不知道的提Issues技巧》](https://github.com/shenliyang/hexo-theme-snippet#你不知道的提Issues技巧)

> 为了能精准定位问题，希望尽量提供一下信息
1. 相关问题截图
2. 有线上环境，建议提供一下网址
3. 如果是兼容bug，建议提供下设备型号，浏览器名称及版本

------- **如果是意见或建议，可以忽略以内容** ------------
# 主题优化疑问
![](https://synp.oss-cn-hongkong.aliyuncs.com/扩大空间问题.png)

文章一级标题前的空间太小，导致文章看上去太挤，请问如何增大一级标题前的空间，使它们看上去更层次分明？

**Comment by shenliyang** [comment]
需要修改样式部分，稍后我统一改下

**Comment by Syngnath** [comment]
> 需要修改样式部分，稍后我统一改下

好的，谢谢！

**Comment by shenliyang** [comment]
您好，由于在规划主题时，通常考虑到h1大标题只会出现文章标题或者顶部处，所有没有设置距离上部间隙，由于不是通用情况，您可以启用主题开发模式，自行配置。
