### ISSUE TITLE
侧边栏添加推广功能

### ISSUE THREAD

**Issue by steley** [shenliyang/hexo-theme-snippet#141]
1. _config.yml添加推广功能

在Widgets-search后添加“- promo”
~~~
# 各个小工具的设置
## widgets
widgets:
  - search
  - promo
~~~

2. _config.yml设置推广

参考网站公告的设置
~~~
## 广告 310*30
promo: 
            <p>
                <a href="/" target="_blank"> <img src="/" alt></a> <br />
            </p>
~~~

3. Snippet/layout/_widget

复制notification.ejs为promo.ejs，然后将文件内的notification改为promo。

4. snippet/languages

default.yml 添加“promo: Promotion”
ja.yml 添加"promo: 販促"
zh-CN.yml 添加“promo: 推广”
zh-TW.yml 添加“promo: 推廣”

5. 效果预览

[![Selection_027.png](https://i.loli.net/2019/05/27/5ceb7752741b010397.png)](https://i.loli.net/2019/05/27/5ceb7752741b010397.png)

**Comment by shenliyang** [comment]
欢迎二次自定义开发。
