### ISSUE TITLE
生成的html代码有误

### ISSUE THREAD

**Issue by ackurdeeve** [shenliyang/hexo-theme-snippet#142]
自动生成的静态网页，在`<body>`之前就提前插入`</html`>，我先以为是自己改动了代码产生的bug。结果发现作者您自己的网页同样存在这样的问题。`</body>`后也没有`</html>`。虽然网页显示正常，但是可能会影响seo正常收录。

```
</head></html>
...
<body><header class="main-header" style="background-image:url(http://snippet.shenliyang.com/img/banner.jpg)">
```

http://prntscr.com/nw5m1m

**Comment by shenliyang** [comment]
![20190601160941](https://user-images.githubusercontent.com/14257483/58745786-38826880-8488-11e9-9c61-e0de2bf1b836.png)

您好，并未发现您描述的问题，请拉取最新代码，如果问题依然存在，希望提供更多信息

**Comment by ackurdeeve** [comment]
发现个问题，我重新装了原版hexo以后就是这样，和主题没关系。。。不知道哪里出了问题
