### ISSUE TITLE
随机缩略图每个文章咋都一样呢

### ISSUE THREAD

**Issue by myitsite** [shenliyang/hexo-theme-snippet#145]
随机缩略图每个文章咋都一样呢
![image](https://user-images.githubusercontent.com/50978153/59656091-1cdcc900-91cf-11e9-9f7e-55bdda7ac489.png)

**Comment by EscapeLife** [comment]
@myitsite 主题默认使用的是文章的第一个图片作为缩略图展示，即`![xxx](xxx.png)`，你确认下是否都为同一个图片链接。
