### ISSUE TITLE
正文添加图片时。图片路径里全部多了一个“.com"，导致图片不能正常实现。但是我这边输入的路径里没有.com。

### ISSUE THREAD

**Issue by uxcoffee** [shenliyang/hexo-theme-snippet#147]
我按照网上的教程_config.yml 里的post_asset_folder:这个选项设置为true之后。开始为正文添加图片。但是图片不能正常显示。F12调试时，发现图片路径里多了一个.com。即是"public\.com\图片.jpg"，正常情况不应该是”public\2019\06\26\图片.jpg“吗？这个.com是在什么地方生成的。另外想请教一下，如果不调用正文的图片作为缩略图，是如何指定要缩略图的？

网站上传失败的网站：uxcoffee.github.io

![](img_url)

**Comment by EscapeLife** [comment]
@uxcoffee 看你已经使用了别的主题了🙁

**Comment by uxcoffee** [comment]
昨天在做问题排除，换了个主题测试。

**Comment by shenliyang** [comment]
有空闲时间，我排查一下
