### ISSUE TITLE
gitalk.ejs配置错误导致无法自动创建issue

### ISSUE THREAD

**Issue by HamptonChen** [shenliyang/hexo-theme-snippet#148]
在gitalk.ejs文件中，关于Gitalk配置的admin一项写错了，不应该是String，导致新文章无法自动创建issue，需要每次自己手动到相应的git repo中去创建，修改为下面写法即可自动创建
`
admin: ["<%= theme.gitalk.admin%>"]
`

**Comment by shenliyang** [comment]
感谢提醒，稍后我会改下

**Comment by youhunwl** [comment]
> 在gitalk.ejs文件中，关于Gitalk配置的admin一项写错了，不应该是String，导致新文章无法自动创建issue，需要每次自己手动到相应的git repo中去创建，修改为下面写法即可自动创建
> `admin: ["<%= theme.gitalk.admin%>"]`

我想问下你配置中的gitalk.admin 是怎么写的 我字符串或者直接书写都提示未定义 gitalk.ejs admin已更改为数组

**Comment by HamptonChen** [comment]
> > 在gitalk.ejs文件中，关于Gitalk配置的admin一项写错了，不应该是String，导致新文章无法自动创建issue，需要每次自己手动到相应的git repo中去创建，修改为下面写法即可自动创建
> > `admin: ["<%= theme.gitalk.admin%>"]`
> 
> 我想问下你配置中的gitalk.admin 是怎么写的 我字符串或者直接书写都提示未定义 gitalk.ejs admin已更改为数组
@
admin: ['HamptonChen']

**Comment by HamptonChen** [comment]
@youhunwl 

admin: ['HamptonChen']

**Comment by youhunwl** [comment]
> @youhunwl
> 
> admin: ['HamptonChen']

已经解决了发现不是这个问题 是我gitalk.ejs那边粗心多了个引号😂，感谢
