### ISSUE TITLE
建议主题添加feed功能

### ISSUE THREAD

**Issue by EscapeLife** [shenliyang/hexo-theme-snippet#149]
可以参考下面👇这个链接

- `https://github.com/ekalinin/sitemap.js`

**Comment by shenliyang** [comment]
好的，谢谢，建议已收到

**Comment by shenliyang** [comment]
您好，hexo已有hexo-generator-feed插件来生成feed，并且是基于站点级，不是主题级，使用和配置也很简单，所有就不继承到主题里了。感谢您的反馈。
更多请访问：[https://github.com/hexojs/hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed)
