### ISSUE TITLE
增加文章占屏比

### ISSUE THREAD

**Issue by yanbinghu** [shenliyang/hexo-theme-snippet#153]
## 你好
首先非常感谢作者的分享，主题很好看，只是发现正文里似乎占屏比比较小，如下：

![企业微信截图_15665413933050](https://user-images.githubusercontent.com/23411939/63571409-b1d6b680-c5b2-11e9-87c8-a754f7a68303.png)

不知能否调整或者告知比较好的调整方式，非常感谢。

**Comment by shenliyang** [comment]
您好，布局是基于bootstrap标准最大宽度1200设计的。因为要考虑不同终端访问的情况，需要兼容适配。
基于上面截图，有可能是您的浏览器进行缩放造成，请调整到缩放100%后再访问试下。

**Comment by yanbinghu** [comment]
## 谢谢回复
不知道是不是和屏幕分辨率有关，在大的显示器里确实显得占屏比非常小。
不过下面评论区的文字确实有点小了
![snippet](https://user-images.githubusercontent.com/23411939/63595035-a4d5b980-c5ea-11e9-9c91-58f37117a840.png)

**Comment by shenliyang** [comment]
主题支持多个评论系统，也可以试一试其他评论系统

**Comment by panhainan** [comment]
layout.ejs文件找到
<div class="container">
添加属性 style="width:80%"，比例根据你自己喜欢的定；
可以查看我的网站 比例为80%：http://sixteen.site
