### ISSUE TITLE
img 加载 设置问题

### ISSUE THREAD

**Issue by s2339956** [shenliyang/hexo-theme-snippet#155]
```
---
title: Analysis .a static library
date: 2019-09-18 12:14:25
categories: ['iOS','app'] 
tags: ['iOS','app']       
comments: true 
img: source/images/Analysis_static_library/Analysis_static_library1.png
---
```

这是我文章中所设置的内容，img 出现无法载入图像问题，请问是我设置错误吗？

**Comment by EscapeLife** [comment]
@s2339956 你需要注意一下图片的相对路径地址，相对于`source`目录而言，比如`source`目录下创建一个`images`目录。使用如下所示：

```bash
---
title: xxx
comments: true
categories: xxx
tags: ssh
img: /images/aliyun-ssh-break.png
abbrlink: xxx
date: xxx
---
```

**Comment by s2339956** [comment]
> @s2339956 你需要注意一下图片的相对路径地址，相对于`source`目录而言，比如`source`目录下创建一个`images`目录。使用如下所示：
> 
> ```shell
> ---
> title: xxx
> comments: true
> categories: xxx
> tags: ssh
> img: /images/aliyun-ssh-break.png
> abbrlink: xxx
> date: xxx
> ---
> ```

谢谢，修正路径为 `/images/Analysis_static_library/Analysis_static_library1.png`，就能顺利载入了。
希望能在说明文档上加上去，避免发生跟我一样的问题～
