### ISSUE TITLE
Valine设置邮件评论，文章评论了，不生效，收不到邮件

### ISSUE THREAD

**Issue by chenshuai1995** [shenliyang/hexo-theme-snippet#156]
> 请先确认以下情况：
- [x] [] 拉取主题最新代码，问题依然存在。
- [x] [] 已经搜索Issues历史记录，并阅读过：[主题常见问题](https://github.com/shenliyang/hexo-theme-snippet#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [] 提Issues前建议先阅读：[《你不知道的提Issues技巧》](https://github.com/shenliyang/hexo-theme-snippet#你不知道的提Issues技巧)

> 为了能精准定位问题，希望尽量提供一下信息
1. 本地主题配置文件

![](https://note.youdao.com/yws/public/resource/8b93771e39cea0687a194620a9446e9d/xmlnote/99BD444E36084E5A8F3028E06278B07D/13706)

2. valine控制台查看用户

![](https://note.youdao.com/yws/public/resource/8b93771e39cea0687a194620a9446e9d/xmlnote/010B5F5A00814873871CB666B3BEFCAC/13707)

3. 个人博客地址

   [<https://chenshuai1995.github.io/>](https://chenshuai1995.github.io/)

**Comment by shenliyang** [comment]
这个是第三方提供的功能，建议查看官网文档和说明： [Valine 评论系统中的邮件提醒设置](https://valine.js.org/notify.html)

**Comment by chenshuai1995** [comment]
> 这个是第三方提供的功能，建议查看官网文档和说明： [Valine 评论系统中的邮件提醒设置](https://valine.js.org/notify.html)

我想问下，是使用的Valine自带的邮件提醒，还是第三方的Valine-Admin，这个是个人开发的。你那个配置的是使用的哪个？

**Comment by shenliyang** [comment]
都有用过，各有优点吧，参照自己的需求和喜好就行了
