### ISSUE TITLE
页面加载报错

### ISSUE THREAD

**Issue by Cloudzp** [shenliyang/hexo-theme-snippet#159]
> 请先确认以下情况：
- [ ] 拉取主题最新代码，问题依然存在。
- [ ] 已经搜索Issues历史记录，并阅读过：[主题常见问题](https://github.com/shenliyang/hexo-theme-snippet#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] 提Issues前建议先阅读：[《你不知道的提Issues技巧》](https://github.com/shenliyang/hexo-theme-snippet#你不知道的提Issues技巧)

> 为了能精准定位问题，希望尽量提供一下信息
1. 相关问题截图
![image](https://user-images.githubusercontent.com/25190767/67300234-3d6fb380-f520-11e9-8e93-b814b076a978.png)
2. 有线上环境，建议提供一下网址
3. 如果是兼容bug，建议提供下设备型号，浏览器名称及版本

------- **如果是意见或建议，可以忽略以内容** ------------

**Comment by Cloudzp** [comment]
public/css目录下没有生成style.css文件
![image](https://user-images.githubusercontent.com/25190767/67305278-ad356c80-f527-11e9-80d5-c6623a275d0b.png)

**Comment by Cloudzp** [comment]
而且为什么会依赖`http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js`
![image](https://user-images.githubusercontent.com/25190767/67305546-14ebb780-f528-11e9-91cb-dae2b03de238.png)

**Comment by shenliyang** [comment]
您好，Snippet主题是不依赖jQuery的，请检查是否使用了他人二次开发的主题；
主题地址：[hexo-theme-snippet](https://github.com/shenliyang/hexo-theme-snippet)
预览：[www.91h5.cc](https://www.91h5.cc)

> 如果问题依然存在，请提供具体链接地址或者文件等具体信息
