### ISSUE TITLE
大佬，怎么在侧边栏添加Google adsence 啊

### ISSUE THREAD

**Issue by sssomeone** [shenliyang/hexo-theme-snippet#160]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shenliyang** [comment]
可以在  `layout ->_widget `下增加一文件，然后在**主题配置文件_config.yml**中配置导入
```yml
## widgets
widgets:
  - 新增文件名称
``

**Comment by MySakure** [comment]
> 可以在 `layout ->_widget `下增加一文件，然后在**主题配置文件_config.yml**中配置导入
> 
> ```yaml
> ## widgets
> widgets:
>   - 新增文件名称
> ``
> ```

thx

**Comment by MySakure** [comment]
> 可以在 `layout ->_widget `下增加一文件，然后在**主题配置文件_config.yml**中配置导入
> 
> ```yaml
> ## widgets
> widgets:
>   - 新增文件名称
> ``
> ```

大佬你好，我太菜了发现不会写。大佬你能大概的演示一下吗，用一个googleadsences的代码？谢谢大佬了

**Comment by shenliyang** [comment]
首先，在以下目录新建一个`googleadsences.ejs`文件，如下图
![微信截图_20191108165809](https://user-images.githubusercontent.com/14257483/68463281-40211700-0249-11ea-9d75-16e170547dd2.png)

然后，打开主题`_config.yml`文件，增加 googleadsences 配置项，如下图
![微信截图_20191108165938](https://user-images.githubusercontent.com/14257483/68463417-88403980-0249-11ea-8c5f-6a2945e44dd2.png)

**Comment by MySakure** [comment]
> 首先，在以下目录新建一个`googleadsences.ejs`文件，如下图
> ![微信截图_20191108165809](https://user-images.githubusercontent.com/14257483/68463281-40211700-0249-11ea-9d75-16e170547dd2.png)
> 
> 然后，打开主题`_config.yml`文件，增加 googleadsences 配置项，如下图
> ![微信截图_20191108165938](https://user-images.githubusercontent.com/14257483/68463417-88403980-0249-11ea-8c5f-6a2945e44dd2.png)

thx，谢谢大佬指点
