### ISSUE TITLE
分页跳转可视化问题

### ISSUE THREAD

**Issue by Crystalaalx** [shenliyang/hexo-theme-snippet#161]
分页显示<i></i>标签，无法显示响应图标，如下图：
![Uploading image.png…]()

**Comment by Crystalaalx** [comment]
<i class='fa fa-angle-left'></i>1234<i class='fa fa-angle-right'></i>

**Comment by Crystalaalx** [comment]
大佬你好！显示的是HTML标签，跳转到上下页的，并不是Font Awesome图标，请问怎么解决呀？

**Comment by Crystalaalx** [comment]
![image](https://user-images.githubusercontent.com/35326449/69207666-a54f0380-0b8b-11ea-8322-bebbc94a4911.png)

**Comment by Crystalaalx** [comment]
已解决，是hexo的版本问题，加了escape属性即可。

**Comment by nsmeng3** [comment]
> 已解决，是hexo的版本问题，加了escape属性即可。
请问 escape属性 怎么加呀
