### ISSUE TITLE
诚邀合作事宜

### ISSUE THREAD

**Issue by zhennann** [shenliyang/hexo-theme-snippet#162]
很喜欢你博客的风格，可否为Cabloy-CMS开发一套（免费/付费）主题，然后发布到Cabloy商店里面？

CabloyJS：是一款顶级NodeJS全栈业务开发框架, 基于KoaJS + EggJS + VueJS + Framework7 
Cabloy-CMS：是基于CabloyJS全栈业务开发框架开发的动静结合的CMS，可以快速构建企业网站、博客、社区、商城等Web应用
Cabloy商店：包括品类广泛的各类模块，满足不同场景的开发需求

CabloyJS介绍：https://cabloy.com/zh-cn/articles/introduce.html
Cabloy-CMS介绍：https://cabloy.com/zh-cn/articles/cms-introduce.html

Cabloy商店运营模式：https://cabloy.com/zh-cn/articles/store.html

**Comment by XellAion** [comment]
兄弟你这个爬虫过分了

**Comment by zhennann** [comment]
谢回复。这不是爬虫。有问必答是我的诚意！

**Comment by shenliyang** [comment]
您好，首先感谢您的认可。如有合作或什么问题，咱邮件沟通

**Comment by zhennann** [comment]
您好，感谢回复。

CabloyJS是NodeJS全栈开源框架。在此基础上实现了Cabloy-CMS，可以创建网站、博客、技术文档，等等。

此外，还搭建了一个线上商店，可以上传免费或者收费的CMS主题模块。

因此，欢迎您能把现有主题移植到Cabloy-CMS，进行更多尝试。

期待继续交流
