### ISSUE TITLE
详情页刷新后右侧目录显示不正常，需要滚动页面恢复显示

### ISSUE THREAD

**Issue by zhangweiii** [shenliyang/hexo-theme-snippet#164]
在demo中可以复现问题

1. 打开带有目录的详情页，比如[](https://www.91h5.cc/archives/47814.html)
2. 滚动到中部
3. Ctrol + R 刷新页面
    > 此时目录模块显示不正常
4. 滚动页面
    > 此时目录回复正常

一下是不正常的样子

![sendpix2.jpg](https://i.loli.net/2019/12/24/4aPtu6IZycQkqWE.jpg)

**Comment by shenliyang** [comment]
这个确实是个问题，之后会修复这块

**Comment by zhangweiii** [comment]
感谢
