### ISSUE TITLE
上一页下一页显示错误

### ISSUE THREAD

**Issue by yeluoshafei** [shenliyang/hexo-theme-snippet#167]
![微信截图_20200411105944](https://user-images.githubusercontent.com/45232170/79033782-97a22500-7be3-11ea-879a-d56c32810ac0.png)

**Comment by shenliyang** [comment]
是否修改过源码？

**Comment by lankning** [comment]
> 
> 
> 是否修改过源码？

Hi, snippet的作者：

我也遇到类似的问题，出现在首页和分类页面。源码没有改动，仅修改了`.yml`配置文件和`source/img`文件夹下的部分图片。

![图片](https://user-images.githubusercontent.com/51734364/129445347-bf182d7d-e2bc-4aa9-a956-e75efcdd024b.png)
![图片](https://user-images.githubusercontent.com/51734364/129445355-4de6e25d-944a-45ca-a320-ef62db324813.png)
![图片](https://user-images.githubusercontent.com/51734364/129445406-45fa9fee-50f0-4a1f-859b-3faef0012714.png)

文章界面的上一篇/下一篇正常，我试着看了一下源码，认为可能是`/layerout/_partial/pagination.ejs`文件有问题（不太会前端，可能找的不对），后来重新clone了源码还是这样。

**Comment by shenliyang** [comment]
请提供下hexo版本号，我稍后排查一下，感谢反馈

**Comment by lankning** [comment]
> 
> 
> 请提供下hexo版本号，我稍后排查一下，感谢反馈

版本号如下：

hexo: 5.4.0
hexo-cli: 4.3.0

![图片](https://user-images.githubusercontent.com/51734364/129448754-e65d1afc-2433-45af-8aeb-15231111a341.png)

感谢！

**Comment by shenliyang** [comment]
该问题已修改，请拉取最新代码

**Comment by lankning** [comment]
非常感谢！

**Comment by lankning** [comment]
非常感谢！
