### ISSUE TITLE
不好意思打扰了，有两个地方我弄了很久还是没弄好，所以还是过来发issues了。。

### ISSUE THREAD

**Issue by Nothing-lin** [shenliyang/hexo-theme-snippet#168]
### 你好，我的这个地方打开是空白的，它的地址需要怎么设置？一般像这里的文章分类需要怎么设置？

</br>

<img src="https://i.loli.net/2020/04/12/f8TqpxbLNg47nAi.png"  width=300>
<img src="https://i.loli.net/2020/04/12/kprWJaP2cdBKRtT.png" width=300>

### 你好，还有我想问一下像首页文章的封面图是怎么设置的？

<img src="https://i.loli.net/2020/04/12/COxPV78ThrEwq5a.png" >

### 打扰了，我看了hexo官方文档和你写的常见问题，我弄了好多天都没有弄好

**Comment by lankning** [comment]
封面图readme文件有说，在头部加入类似 
```
img: http://abc.com/1.jpg
```
的写法即可即可
