### ISSUE TITLE
标签有问题

### ISSUE THREAD

**Issue by niume** [shenliyang/hexo-theme-snippet#2]
生产标签的时候，显示undefinedtags

**Comment by shenliyang** [comment]
是否可以描述的再详细一点，发生的位置？是否可以提供相关截图？

**Comment by niume** [comment]
生成的 标签，路径不对。

**Comment by niume** [comment]
路径本来应该是tabs。但是他生成的显示undefinedtags。

**Comment by shenliyang** [comment]
### 您好，在您的网站里并未复现该标签问题。请排查以下相关问题：

##### 根目录下_config.yml相关配置，此问题可能是上一级目录配置造成的

permalink | 文章的 永久链接 格式 | :year/:month/:day/:title/
-- | -- | --

更多配置请参考：[hexo 配置文档](https://hexo.io/zh-cn/docs/configuration.html)

**Comment by dynasty-x** [comment]
@niume 我也遇到这个问题，找到问题在哪了吗？

**Comment by dynasty-x** [comment]
## 不知道哪里少了根目录配置，暂时用下面的方法解决：
1. 找到node_modules中的url_for.js文件
2. 把`var root = config.root;` 改为 `var root = config.root || '/';`

## 哪位大哥找到问题所在，求分享

**Comment by shenliyang** [comment]
@niume @dynasty-x  该 Bug 已修复！
