### ISSUE TITLE
comments 无法开启？是不支持吗

### ISSUE THREAD

**Issue by wyxy2005** [shenliyang/hexo-theme-snippet#21]
comments 无法开启？是不支持吗

**Comment by jiangningstar** [comment]
@wyxy2005 主题配置gitment是可以使用的  友言的话是有问题的 第三方友言的服务器有故障 
![image](https://user-images.githubusercontent.com/16531977/34411203-31dcae30-ec10-11e7-813a-f21e6912d802.png)
我对主题做了修改 支持 disqus, 可以自己找第三方的评论系统即可

**Comment by shenliyang** [comment]
现在是第三方友言出现不稳定造成的，下个推送版会对评论系统进行整合，增加更多第三方评论系统。方便扩展及配置，感谢反馈。

**Comment by shenliyang** [comment]
第三方评论系统已整合
