### ISSUE TITLE
可不可以加一个时间轴的功能呀

### ISSUE THREAD

**Issue by Nash-x9** [shenliyang/hexo-theme-snippet#22]
emmmm 希望可以加入时间轴功能。。可以自定义时间轴，根据文章生成俩种。。我觉得这是next里面我比较中意的地方。。只是希望。。祝好

**Comment by shenliyang** [comment]
增加一个功能会考虑各个终端显示，兼容，是否需要添加侵入式代码，是否影响性能等方面的考虑，后期会综合一下，考虑是否添加，感谢你的建议，谢谢

**Comment by Nash-x9** [comment]
谢谢你的回复！PS：目前四字导航手机兼容性 稍微有点问题。

**Comment by shenliyang** [comment]
@Nash-x9  :sweat_smile:  已增加文章归档时间轴，久等了

**Comment by Nash-x9** [comment]
非常感谢！很久没写博客了。回头更新一下～

**Comment by shenliyang** [comment]
:thumbsup:
