### ISSUE TITLE
hello，这个没有分页功能吗？

### ISSUE THREAD

**Issue by ryanlijianchang** [shenliyang/hexo-theme-snippet#28]

**Comment by shenliyang** [comment]
主题已经集成分页功能，在Hexo根目录下修改 _config.yml 的配置

| 参数       | 描述        | 默认值  |
| ------------- |:-------------:| :-----:|
| per_page     | 每页显示的文章量 (0 = 关闭分页功能) |  10 |
| pagination_dir     | 分页目录      |   page |

**Comment by shenliyang** [comment]
更多主题相关问题请参考：

- [Hexo 官方文档](https://hexo.io/zh-cn/docs/)
- [hexo-theme-snippet 配置文档](https://github.com/shenliyang/hexo-theme-snippet/blob/master/README.md)
