### ISSUE TITLE
嗨，哥们儿，有空对搜索优化吗？

### ISSUE THREAD

**Issue by smartsean** [shenliyang/hexo-theme-snippet#32]
很喜欢你这个博客主题，现在本地搜索和google搜索都不能用，有空优化下吗？谢谢

**Comment by shenliyang** [comment]
### 本地搜索：
如果要使用本地站点搜索，必须安装插件hexo-generator-json-content来创建本地搜索json文件
#### 安装方式：
` npm i hexo-generator-json-content@2.2.0 -S`

然后修改主题配置_config.yml文件下jsonContent相关参数。

### 谷歌搜索：
如果不能使用谷歌搜索，确定是否已经科学上网

更多请参考：[Snippet主题配置](https://github.com/shenliyang/hexo-theme-snippet/blob/master/README.md)

**Comment by smartsean** [comment]
@shenliyang 是这样的，本地搜索可以了，但是google搜索有问题，默认应该不是搜索站点的吧，看下面的图片
![图片](https://user-images.githubusercontent.com/13332887/34973170-47aaea5a-fac1-11e7-987d-db2ca8e21a10.png)

**Comment by smartsean** [comment]
好的，谢谢。我自己关了。
