### ISSUE TITLE
搜索结果的标题关键字能不能设置高亮？

### ISSUE THREAD

**Issue by jiujiubad** [shenliyang/hexo-theme-snippet#36]
比如在我的博客http://jiujiubad.top。

想搜“搜索”这个关键词，结果只有内容部分相匹配的关键词会高亮橙色，标题部分能不能设置高亮，而且最好是高亮另一种颜色？

PS：炒鸡喜欢这个主题，感觉综合美观和入手速度完爆Next。

**Comment by shenliyang** [comment]
:smile:  还没来得及写匹配搜索结果标题，下一版会加上

**Comment by shenliyang** [comment]
已增加对标题检索
