### ISSUE TITLE
嗨，我的博客分类会错乱，如图

### ISSUE THREAD

**Issue by smartsean** [shenliyang/hexo-theme-snippet#38]
如图所示，一个分类显示了多次。
![image](https://user-images.githubusercontent.com/13332887/35676103-80dff114-0785-11e8-8ea7-a36ef06594ab.png)

博客中我是这样写的：
![image](https://user-images.githubusercontent.com/13332887/35676142-a7d2d84a-0785-11e8-8348-60dc83639239.png)

**Comment by shenliyang** [comment]
只有文章支持分类和标签，您可以在 Front-matter 中设置。在其他系统中，分类和标签听起来很接近，但是在 Hexo 中两者有着明显的差别：分类具有顺序性和层次性，也就是说 Foo, Bar 不等于 Bar, Foo；而标签没有顺序和层次。
```
categories:
- Diary
tags:
- PS3
- Games
```

**Comment by smartsean** [comment]
@shenliyang 好的，多谢你的回复。
