### ISSUE TITLE
在url哪里可以访问到本地静态文件吗？

### ISSUE THREAD

**Issue by yuanchengjs** [shenliyang/hexo-theme-snippet#39]
就是类似通过static文件夹搭载一些项目预览或者pdf之类的

**Comment by shenliyang** [comment]
在主题 `source` 目录下新建文件夹，例如:  `static`文件夹，然后添加静态资源，例如: hexo.pdf文件， 访问：`http://yoursite.com/static/hexo.pdf`

**Comment by yuanchengjs** [comment]
thanks !
