### ISSUE TITLE
建议加一个MD 目录命令识别，目前识别不了

### ISSUE THREAD

**Issue by youhunwl** [shenliyang/hexo-theme-snippet#41]
[TOC]  这个  或者能自动在文章页面左侧或者右侧加个也行 不然阅读体验太不好了

**Comment by shenliyang** [comment]
目前没有想到适合方案。
子标题文字过长，显示省略号是否合适？
文章层级较多TOC目录内容过高如何处理？
移动端如何平滑过渡？
目录放在widget中，加入tab切换是否增加用户操作？
目录有不可控因素，如否有好的建议？

**Comment by youhunwl** [comment]
你把我说的无话了，哈哈  不过还是很喜欢这个主题  第一次折腾hexo发现上手这么顺利

**Comment by shenliyang** [comment]
:smile:  主题得考虑各种极端情况，你可以fork后自己加一下，自己博客，毕竟是可控的。

**Comment by youhunwl** [comment]
嗯嗯 谢谢
