### ISSUE TITLE
继续提点小建议

### ISSUE THREAD

**Issue by xiaomubiao** [shenliyang/hexo-theme-snippet#42]
看到 文章下的 分区 和 tag 都加了链接，谢谢作者支持，再提点细节小建议
1、每篇文章 下面的 上一篇 下一篇 西面建议把相关标题加上，感觉对于 SEO 和 留住 访客都有好处
2、导航条上面的文字感觉可以大一点 ，加粗，毕竟是导航 醒目一点
3、网站公告功能不错，可以做成 广告位 ，hexo 替代 wp  感觉 广告功能弱了点，尤其是我还没发现比较好的商业兴致的主题，我觉得咱们的主题很大气，可以加重一点商业气息，技术博客 就算推荐推荐 VPS 也是好的
4、首页文章摘录 的日期上下都有乐 感觉 可以去掉一个
预祝新年快乐，空间域名都弄好了，年后做几个站试试效果

**Comment by shenliyang** [comment]
感谢建议
