### ISSUE TITLE
导航样式在小屏幕兼容问题

### ISSUE THREAD

**Issue by wuwei1994625** [shenliyang/hexo-theme-snippet#43]
.main-navigation .menu li {
    display: block;
    width: 33%;
    float: left;
  }
改成 
  .main-navigation .menu li {
    display: block;
    width: 100%;
    float: left;
   text-align:center;
   margin-left: -10px;
  }
稍微好看一些

**Comment by shenliyang** [comment]
根据自己网站实际情况可以自行调整，后期会专门优化这里的:smile:
