### ISSUE TITLE
怎么设置首页文章缩略图自动检索文章内图片，不随机选择图片啊，可以固定么？

### ISSUE THREAD

**Issue by lehuiwu** [shenliyang/hexo-theme-snippet#49]
首页文章缩略图自动检索文章内图片，支持自动随机图片，怎样取消随机选择图片

**Comment by nygula** [comment]
判断首页的post列表的缩略图.
好像用默认的thumbnail: 的比较多.
用img: 的比较少.
要不把thumbnail也加进去吧.

修改的地方应该是这里:
hexo-theme-snippet\layout\index.ejs
var _photoUrl = post.img || (urls.length > 0 && urls[random]) || (urls2.length > 0 && urls2[random2]) || '';
