### ISSUE TITLE
文章中有图片，如何列表不显示缩略图

### ISSUE THREAD

**Issue by woshilinqin** [shenliyang/hexo-theme-snippet#54]
测试发现，无图文章，列表没有图
                  有图文章，随机图
                   设置img，以img为主

问：如何让无图文章不要列表图。

**Comment by shenliyang** [comment]
答：参照你的说第一条

**Comment by woshilinqin** [comment]
抱歉说错了，应该是有图片的文章，但是不想要缩略图。一个个设置img太麻烦了

**Comment by shenliyang** [comment]
确实未考虑该需求，如果不想设置Front-matter中的'img'字段，建议去掉源码缩略图逻辑。
