### ISSUE TITLE
建议：文章目录的显示问题

### ISSUE THREAD

**Issue by dinphy** [shenliyang/hexo-theme-snippet#57]
建议：当有使用 “#”号作为标记时，才显示文章目录，如果文章没有使用 “#”号作为标记，应该隐藏

**Comment by shenliyang** [comment]
在文章何处标记？

**Comment by dinphy** [comment]
我的意思就是，你怎么获取元素来生成的目录，当文章中没有生成目录所需要的元素时，文章中就不显示文章目录，虽然你这个也有这样的效果了，但有BUG，会显示文章目录这个标题在文章右上方，实际上目录没有项目，是空的。

**Comment by shenliyang** [comment]
感谢推送
