### ISSUE TITLE
分类文章缩略图

### ISSUE THREAD

**Issue by caojiantao** [shenliyang/hexo-theme-snippet#6]
导航栏分类文章缩略图不显示，91前端网->前端分类，但是在首页是有显示的

**Comment by shenliyang** [comment]
你好，为了考虑首页美观，文章分类的简洁性，缩略图显示规则如下：
首页缩略图显示顺序的规则为：自定义 > 文章内图片 > 随机图片 > 无图文章列表。
文章分类缩略图：如果没有在Front-matter 自定义图片链接，默认显示为无图文章列表模式。
