### ISSUE TITLE
是否支持为一篇文章添加多个分类？

### ISSUE THREAD

**Issue by poorpool** [shenliyang/hexo-theme-snippet#60]
当我试图为一篇文章添加两个categories“图论——基环树”和“动态规划——树形dp”时
![pic1](https://i.loli.net/2018/07/02/5b3a209aeeae1.png)
我发现只显示一个分类
![pic2](https://i.loli.net/2018/07/02/5b3a209af15c8.png)
虽然这篇文章好像添加进了categories
![pic3](https://i.loli.net/2018/07/02/5b3a209b0d343.png)
但是并没有找到
![pic4](https://i.loli.net/2018/07/02/5b3a209b12d13.png)
（图中的文章是很早以前的，那个只有一个分类。我新发布的并没有出现）

**Comment by shenliyang** [comment]
### 分类方法的分歧
如果您有过使用WordPress的经验，就很容易误解Hexo的分类方式。WordPress支持对一篇文章设置多个分类，而且这些分类可以是同级的，也可以是父子分类。但是Hexo不支持指定多个同级分类。下面的指定方法：
```
categories:
- Diary
- Life
```
会使分类Life成为Diary的子分类，而不是并列分类。因此，有必要为您的文章选择尽可能准确的分类。

> 更多关于分类和标签说明请参照  [Hexo官方文档](https://hexo.io/zh-cn/docs/front-matter.html#分类和)

**Comment by poorpool** [comment]
好吧orz，我的问题
