### ISSUE TITLE
【功能性】文章目录太长且无法拖动，导致显示不全

### ISSUE THREAD

**Issue by EscapeLife** [shenliyang/hexo-theme-snippet#64]
这篇博客的内容是对`HTML`基础的一个总结，所有目录比较多，发现右侧文章目录区域无法，且无法拖动显示全部目录信息。如下图所示：

![png](https://user-images.githubusercontent.com/16237571/42302788-a0a967f8-804f-11e8-923b-bfb69447b339.png)

另外问下，如何打赏呢？哈哈哈🙃

**Comment by shenliyang** [comment]
该问题有时间会尽快修复！

**Comment by EscapeLife** [comment]
@shenliyang  snippet很棒，感谢！

**Comment by dinphy** [comment]
该问题我已经修复了，可以看我forks过去的commit

**Comment by dinphy** [comment]
在#articel-toc下加入如下三行:
```js
top: 0px;
bottom: 140px;
overflew-y: auto;
```
目的是让目录框溢出部分自动滚动

**Comment by shenliyang** [comment]
@EscapeLife  主题已修复该问题，如果引用dinphy方案记得修改为：
```
overflew-y: auto -> overflow-y: auto
```
@dinphy 感谢提供修改方案

**Comment by EscapeLife** [comment]
@dinphy 感谢修改方案
@shenliyang 确认没有问题，可以使用。
