### ISSUE TITLE
用这个主题遇见两个问题

### ISSUE THREAD

**Issue by fanqinlong** [shenliyang/hexo-theme-snippet#67]
1. 在chorme浏览器下一直控制台一直报错
inject.preload.js:373 GET blob:http://localhost:4000/8dbf3821-ba7f-40cc-b1a7-607932651656 0 

2. 当点击其他的页面进入页面详情是出现错误
search.js?rev=@@hash:8 Uncaught TypeError: Cannot read property 'innerHTML' of null
    at search.js?rev=@@hash:8
    at search.js?rev=@@hash:143
报错位置在
searchTpl = document.getElementById('search-tpl').innerHTML,

**Comment by dinphy** [comment]
没遇到啊

**Comment by fanqinlong** [comment]
我更新了最新的主题代码，问题就没有了，谢谢您哈
