### ISSUE TITLE
说明

### ISSUE THREAD

**Issue by caojiantao** [shenliyang/hexo-theme-snippet#7]
发现：
分类文章缩略图预加载图（gif）未展示应该是相对路径级别掉了一级，导致不展示；

提问：
我自己用的该主题但“标签云链接”（首页和文章内）有问题，多了个undefined，不知道哪里配置不对，个人博客地址caojiantao.com；

建议：
增加关键词搜索栏；

我只是个小白，觉得这款主题很棒，提点意见，希望更好，哈哈哈哈~

**Comment by shenliyang** [comment]
首先，非常感谢你的反馈和支持。
1.现在只有首页加入懒加载，标签和分类页后续会加上…
2.没点出来
3.用hexo就是追求简洁，极致！该主题还有许多细节和性能需要优化。不是技术大牛😂，感觉还用不到搜索栏，将来有可能会加上吧！
如果喜欢折腾，建议wordpress走起 
[我的博客 www.shenliyang.com](http://www.shenliyang.com)
