### ISSUE TITLE
浏览器查看tags下文件源码和本地生成的tags文件源码怎么不一样呢？

### ISSUE THREAD

**Issue by Jonyker** [shenliyang/hexo-theme-snippet#70]
********************************************
文章开头是这样配置的
---
title: 解决merge冲突
date: 2017-03-17 12:40:30
updated: 2018-07-18 10:05:00
categories: 
- 后端
tags:  
- Git
comments: false
---
********************************************

问题是：
********************************************
本地生成的文件tags面下的文件，生成不是当前tag的文章链接啊

        <div class="post-content">
            <div class="post-head home-post-head">
                <h1 class="post-title"> 
                    <a href="/2018/07/18/Command/命令行的基本格式/">命令行的基本格式</a>
                </h1>
                <div class="post-meta">  &bull;
                    <time class="post-date" datetime="" title="">
                        2018年07月18日
                    </time>
                </div>
            </div>
            <p class="brief">
********************************************

**Comment by shenliyang** [comment]
缓存问题，已解决
