### ISSUE TITLE
为什么我的布局没有适应整个屏幕呢？需要改动代码吗？

### ISSUE THREAD

**Issue by XianlongQi** [shenliyang/hexo-theme-snippet#71]
我clone下来的，两边留白太多了，显得小气
![image](https://user-images.githubusercontent.com/11680813/43237457-7b601906-90bc-11e8-8b20-fd01fc29360a.png)

想要下面的效果
![image](https://user-images.githubusercontent.com/11680813/43237537-d89526ca-90bc-11e8-8be8-8ebe11fcfbab.png)

谢谢楼主！

**Comment by shenliyang** [comment]
请确认是否对浏览器视窗进行了缩放？

**Comment by XianlongQi** [comment]
额，不好意思，确实是缩放了，sorry
