### ISSUE TITLE
gulp报错

### ISSUE THREAD

**Issue by zzqzzqzzqsc03** [shenliyang/hexo-theme-snippet#76]
### 该问题是怎么引起的？
在用gulp命令时，报错

### 重现步骤
按照README执行

### 报错信息
module.js:549
    throw err;
    ^

Error: Cannot find module 'gulp-less'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at F:\Workspaces\hexo\gulpfile.js:4:16
    at Object.<anonymous> (F:\Workspaces\hexo\gulpfile.js:108:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by shenliyang** [comment]
没有安装依赖 现在`npm install`

**Comment by shenliyang** [comment]
没有安装依赖，先 `npm i` 一下

**Comment by shenliyang** [comment]
请参照最新文档 [hexo-theme-snippet#部署主题](https://github.com/shenliyang/hexo-theme-snippet#4-%E9%83%A8%E7%BD%B2%E4%B8%BB%E9%A2%98)

**Comment by gaomysion** [comment]
遇见了通用的情况，安装依赖没用。

**Comment by gaomysion** [comment]
package.json 中并没有依赖的模块，因此npm install 也不会安装

**Comment by gaomysion** [comment]
less = require('gulp-less'),
        rename = require('gulp-rename'),
        minifycss = require('gulp-minify-css'),
        autoprefixer = require('gulp-autoprefixer'),
        uglify = require('gulp-uglify'),
        jshint = require('gulp-jshint'),
        stylish = require('jshint-stylish'),
        notify = require('gulp-notify'),
        plumber = require('gulp-plumber'),
        htmlclean = require('gulp-htmlclean'),
        htmlmin = require('gulp-htmlmin'),
        rev = require('gulp-rev-append'),
        sequence = require('gulp-sequence'),
        path = require('path'),

难道需要安装这些所有的模块吗？
以下是package.json 没用这些模块
{
    "name": "hexo-theme-snippet",
    "version": "1.2.1",
    "description": "Snippet 简洁而不简单，也许是一款你寻找已久的hexo主题",
    "author": "shenliyang",
    "license": "MIT",
    "private": true,
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/shenliyang/hexo-theme-snippet.git"
    },
    "bugs": {
        "url": "https://github.com/shenliyang/hexo-theme-snippet/issues"
    },
    "homepage": "https://github.com/shenliyang/hexo-theme-snippet#readme"
}

**Comment by zzqzzqzzqsc03** [comment]
谢谢
