### ISSUE TITLE
腾讯分析

### ISSUE THREAD

**Issue by zzqzzqzzqsc03** [shenliyang/hexo-theme-snippet#77]
### 该问题是怎么引起的？
怎么使用腾讯分析？？？

### 重现步骤
ta让我粘贴这个<script type="text/javascript" src="http://tajs.qq.com/stats?sId=65971078" charset="UTF-8"></script>

### 报错信息
不知道怎么办？？？

**Comment by shenliyang** [comment]
在主题配置文件中`tencent_analytics:` +你申请的sId

**Comment by zzqzzqzzqsc03** [comment]
谢谢，好了
