### ISSUE TITLE
Travis CI 

### ISSUE THREAD

**Issue by zzqzzqzzqsc03** [shenliyang/hexo-theme-snippet#78]
请问，怎么用Travis CI 上传文章？？？
（本人英语不好，orz）

**Comment by shenliyang** [comment]
可参照：[手把手教你使用Travis CI自动部署你的Hexo博客到Github上](https://blog.csdn.net/woblog/article/details/51319364)

**Comment by zzqzzqzzqsc03** [comment]
但是还是不知道怎么构建

**Comment by zzqzzqzzqsc03** [comment]
git push origin blog-source:blog-source  这步执行不了

**Comment by shenliyang** [comment]
不使用Travis CI不影响博客和主题的正常使用。也可以多研究一下
