### ISSUE TITLE
希望优化标签的展示功能

### ISSUE THREAD

**Issue by EscapeLife** [shenliyang/hexo-theme-snippet#79]
## 1. 出现问题

- 博客数量过多之后，标签展示太长，如下所示

![snip20180907_1](https://user-images.githubusercontent.com/16237571/45193351-27e9ec80-b280-11e8-9122-9ea90fd4df05.png)

## 2. 改进建议

-  之前在`Issue`的提问中，看到`@dinphy`他优化了标签的展示功能
- 很漂亮而且很实用，为`hexo-theme-snippet`增色不少，希望在这里能够增加
- 如下所示是`@dinphy`他的博客地址链接 - [乐于分享](http://www.dinphy.wang/)

![default](https://user-images.githubusercontent.com/16237571/45193501-e148c200-b280-11e8-8251-ab368d8204ed.png)

## 3. 感谢各位

- 感谢大佬们的`hexo-theme-snippet`主题，赞一个哈！

**Comment by EscapeLife** [comment]
@dinphy 希望能将标签云功能添加到`hexo-theme-snippet`主题，感谢哈！

**Comment by shenliyang** [comment]
感谢反馈，对于标签云动画特效，个人感觉除了炫酷并不太理想，后期会添加到主题，用户可以选择是否开启。

**Comment by EscapeLife** [comment]
@shenliyang  @dinphy   看到了，但是效果不理想，很卡很卡，而且标签没有去重，很多重复的标签。
![image](https://user-images.githubusercontent.com/16237571/45261125-b307e580-b42c-11e8-9df8-79f22ecb499d.png)

**Comment by shenliyang** [comment]
使用DOM操作方式，确实有种卡顿的感觉，已更换使用canvas生成方式。

**Comment by EscapeLife** [comment]
@shenliyang  自测效果确实很好，感谢能够抽时间修改，小花花送给你哈！
