### ISSUE TITLE
分类显示不正确

### ISSUE THREAD

**Issue by JiBaoBao** [shenliyang/hexo-theme-snippet#82]
楼主您好，我的分类显示不正确，大致情况如下：

我有一共有23篇博客，其中3篇博客属于['分类A','分类B']，另外20篇博客属于['分类A']，
然后在右侧标签分类一栏中，显示的样式为
```
分类B (3篇)
分类A (3篇)
分类A (20篇)
```
问题就是，可否将“分类A”部分都做合并处理？
想要显示成如下样式：
```
分类B (3篇)
分类A (23篇)
```

**Comment by shenliyang** [comment]
Hexo文档：[分类和标签](https://hexo.io/zh-cn/docs/front-matter#分类和标签)
