### ISSUE TITLE
关于首页文章列表缩略图url跟分类页面下文章列表缩略图url不一致的问题

### ISSUE THREAD

**Issue by guard-wen** [shenliyang/hexo-theme-snippet#83]
### 该问题是怎么引起的？
我的网站根目录是http://xxx.com/blog 我给文章设置了缩略图,路径为img: /img/helloworld.jpg，该文章在首页文章列表显示的路径为/blog/img/helloworld.jpg, 显示正常。 在分类页面下的文章列表显示路径为/img/helloworld.jpg  路径错误。

**Comment by shenliyang** [comment]
代码已修复，稍后请更新一下。
