### ISSUE TITLE
翻页之后，顶部的 head-img 显示不出来，希望看看

### ISSUE THREAD

**Issue by ctimbai** [shenliyang/hexo-theme-snippet#85]
**Describe the bug**
首先感谢大佬提供这么好的主题，我遇到个问题，就是翻页之后，顶部的 head-img 显示不出来，有一块空间空出来但不显示东西。

**Comment by shenliyang** [comment]
好的，已收到问题，感谢反馈

**Comment by iclouddev** [comment]
你好，这个问题什么时候能解决好呢？

**Comment by shenliyang** [comment]
关闭的issue，问题都已解决，请更新代码。
