### ISSUE TITLE
自己开发那边是否能详细一点， 我想改改看

### ISSUE THREAD

**Issue by HongTao-Huang** [shenliyang/hexo-theme-snippet#86]
我在主题下执行了npm install
然后gulp dev
再然后回到根目录执行 hexo c， hexo g， hexo s -p 4000
但是打开网页端4000的时候，  这边监听会报一堆错， 网页打不开
我的系统时mac os ，  请问一下不知道哪里的问题？
![image](https://user-images.githubusercontent.com/34468350/46207419-e669d000-c359-11e8-8964-74523211b08e.png)

**Comment by shenliyang** [comment]
建议拷贝主题目录下的package.json和gulpfile.js文件到项目主目录，然后npm i 试一下

**Comment by HongTao-Huang** [comment]
可以了， 非常感谢🙏



开 2018年9月29日 在 08:59:47, shenliyang (notifications@github.com<mailto:notifications@github.com>) 写到:

建议拷贝主题目录下的package.json和gulpfile.js文件到项目主目录，然后npm i 试一下
