### ISSUE TITLE
主题分类只显示一个类别标签

### ISSUE THREAD

**Issue by EscapeLife** [shenliyang/hexo-theme-snippet#89]
### 1. 问题概述

今天创建博客的时候，给文章中添加了两个类别标签，但是发现主题中只显示了一个，且为最后一个。具体，详见如下截图。

### 2. 截图说明

<img width="790" alt="jietu20181014-095243" src="https://user-images.githubusercontent.com/16237571/46911751-d5df6980-cf97-11e8-834a-fe61c760abad.png">

<img width="759" alt="jietu20181014-095322" src="https://user-images.githubusercontent.com/16237571/46911757-f4ddfb80-cf97-11e8-8fc3-8e94ff04258b.png">

### 3. 反馈意见

感觉只显示一个不是很合理，希望能够支持多类别展示，😝

**Comment by shenliyang** [comment]
[关于Hexo标签和分类方法的分歧](https://github.com/shenliyang/hexo-theme-snippet#7-%E5%85%B3%E4%BA%8Ehexo%E6%A0%87%E7%AD%BE%E5%92%8C%E5%88%86%E7%B1%BB%E6%96%B9%E6%B3%95%E7%9A%84%E5%88%86%E6%AD%A7)

**Comment by EscapeLife** [comment]
@shenliyang  Thanks.
