### ISSUE TITLE
网站的语言

### ISSUE THREAD

**Issue by yefan-abcdefg** [shenliyang/hexo-theme-snippet#92]
### 该问题是怎么引起的？

执行hexo s -g后，网站的语言会变，概率发生的。请问是怎么回事，我已经改成zh-CN了。

### 报错信息

无

**Comment by shenliyang** [comment]
在hexo server 命令下没有 -g 选项，请参照： [Hexo server指令](https://hexo.io/zh-cn/docs/commands#server)
建议：启动本地服务和生成静态文件分开执行，如果执行并行命令请使用`&`

**Comment by yefan-abcdefg** [comment]
嗯呢 好的谢谢

**Comment by yefan-abcdefg** [comment]
> 在hexo server 命令下没有 -g 选项，请参照： [Hexo server指令](https://hexo.io/zh-cn/docs/commands#server)
> 建议：启动本地服务和生成静态文件分开执行，如果执行并行命令请使用`&`

好的 谢谢
