### ISSUE TITLE
snippet主题只有首页的头部背景图片显示,其他前端,后端等页面的头部背景图不显示

### ISSUE THREAD

**Issue by wock1987** [shenliyang/hexo-theme-snippet#94]
作者,你好,首先很感谢你的这套主题,现在遇到一点问题,请教一下,希望能解答:snippet主题只有首页的头部背景图片显示,其他前端页面,后端页面等的头部背景图都不显示,请问这是什么原因?

**Comment by shenliyang** [comment]
1. 请提供hexo配置文件中url和root的配置比如：
```
url: http://www.91h5.cc
root: /
```
2. 项目文件是否放在子目录下面？
3. 请提供相关问题截图

**Comment by wock1987** [comment]
1.![image](https://user-images.githubusercontent.com/36872714/50276631-5ed5be00-047d-11e9-9843-35d97b699935.png)
2.项目放在了正确位置
3.
![image](https://user-images.githubusercontent.com/36872714/50276702-89277b80-047d-11e9-8014-9234098f585d.png)
![image](https://user-images.githubusercontent.com/36872714/50276750-aa886780-047d-11e9-8d56-4ff54959b3e0.png)
4.项目目前是在本地运行的

**Comment by shenliyang** [comment]
在主题 `_config.yml` 配置文件中设置头部banner地址时，建议先使用绝对路径

```Bash
## 设置banner背景图片
banner:
    img: http://snippet.shenliyang.com/img/banner.jpg
```

**Comment by shenliyang** [comment]
已增加对本地资源相对地址的支持，也可更新最新代码。

**Comment by shenliyang** [comment]
主题使用Less编写，建议在less文件下修改样式。
