### ISSUE TITLE
部分社交图标不显示

### ISSUE THREAD

**Issue by liaochenlanruo** [shenliyang/hexo-theme-snippet#99]
**Describe the bug**
社交图标按同样方法设置，但总有一两个无法显示，尤其是researchgate，请问是什么问题，谢谢！

**Comment by shenliyang** [comment]
您好，是由于Font Awesome暂未提供ResearchGate及相关图标，造成未能正常显示。

![20190112153642](https://user-images.githubusercontent.com/14257483/51070712-e085c980-1680-11e9-844e-4ea248a9d28e.png)

> 建议以下解决方案：
1.  到[Font Awesome 中文网](http://www.fontawesome.com.cn/faicons/)，找类似图标代替。
2.  如果确实需要，建议给官方发送 dave@fortawesome.com 增加图标邮件，本主题会同步更新。

**Comment by liaochenlanruo** [comment]
谢谢大佬解答，源您的主题越做越好！
